# This file configures the encryption keys used by sops-nix
# It determines which keys can encrypt/decrypt which files

creation_rules:
  # Default rule for all files in the secrets directory
  - path_regex: secrets/.*
    # List of GPG keys that can encrypt/decrypt secrets
    pgp: >-
      1C9145DA3075392EBA7E271469B16C8E0113CBA2 # ex1tium@outlook.com
